name: run python file

on:
  issues:
      types:
        - opened

jobs:
  python_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests
      - name: run code
        run: python test.py
